### ISSUE TITLE
Deduction Changes: Deduction Start & Deduction End 

### ISSUE THREAD

**Issue by Atsilah** [Bizsmartech/DMS2023#1]
103.75.190.118
user:dmsuser
pass:dms@user

Path: http://103.75.190.118/CloudUApps22/Deduction/AddDeduction
![image](https://github.com/Bizsmartech/DMS2023/assets/111037848/fb9df218-6821-42d4-8eb7-8c9a4031cd30)

**Deduction Start:**
Initially Sasindu make it as auto filled after user select DMID, 

https://github.com/Bizsmartech/DMS2023/assets/111037848/439ff734-030c-4f55-aa6f-8d60d36b4366

but for now client ask to:
1. change this field from dropdown to **textbox** (also allow them to change the date) and please state the format of date : YYYY/MM
For instance, if a user chooses DMID 202308, Deduction Start will automatically be filed as 202308, but they are able to change it to 202309.
Please keep in mind that DMID is the date on which they modify the deduction; it is not always the same as Deduction Start. 
;
Next **Deduction End**:
1. Change to Textbox, and also state the format of date : YYYY/MM

**Do not allowed user insert the other date format 
***Deduction start: Only allowed user to insert present/ future date only. 
****Deduction End: Date insert need to be more than date inserted in Deduction Start. 

SP: INS_ADD_DEDUCTION 
duplicate this sp to make changes. do not change this sp without any backup

**Comment by induwara99** [comment]
https://github.com/Bizsmartech/DMS2023/assets/62685893/b4fb6cf1-9da0-4626-94f1-5f7562c115b0

All done!
