### ISSUE TITLE
Deduction Report: Paging

### ISSUE THREAD

**Issue by Atsilah** [Bizsmartech/DMS2023#10]
Default to 50 entries 
![image](https://github.com/Bizsmartech/DMS2023/assets/111037848/568ac6bf-8023-49cf-921a-d4c773939452)

**Comment by induwara99** [comment]
DONE!

https://github.com/Bizsmartech/DMS2023/assets/62685893/fdf4333b-78d2-4b23-a282-07335e391d3a
