### ISSUE TITLE
New Page: Import Deduction Changes

### ISSUE THREAD

**Issue by Atsilah** [Bizsmartech/DMS2023#11]
![image](https://github.com/Bizsmartech/DMS2023/assets/111037848/b4291675-5570-4029-8d82-c1ef0d6c4087)

after user upload the file, the list need to shown in deduction list ( http://103.75.190.118/CloudUApps22/Deduction/AddDeduction)

*make sure DMID is based on the uploaded month

*format and example
[Deduction-sept 2023.xlsx](https://github.com/Bizsmartech/DMS2023/files/12331089/Deduction-sept.2023.xlsx)

**Comment by induwara99** [comment]
Up to Now Process only have to do the save part!

https://github.com/Bizsmartech/DMS2023/assets/62685893/b09beaac-4fd5-430f-b2a8-e33e8577be66

**Comment by Atsilah** [comment]
@induwara99  for radio button . Hide/remove the manual option and always let computerize option checked. 
Basically Mr Thiru dont want user to upload the manual.

**Comment by induwara99** [comment]
> @induwara99 for radio button . Hide/remove the manual option and always let computerize option checked. Basically Mr Thiru dont want user to upload the manual.

Understood on it!

**Comment by induwara99** [comment]
All Done!


https://github.com/Bizsmartech/DMS2023/assets/62685893/15a52257-9cd5-471d-91d0-0340c0b91bda
