### ISSUE TITLE
Cooperative Cannot Delete

### ISSUE THREAD

**Issue by Atsilah** [Bizsmartech/DMS2023#13]
Path: http://103.75.190.118/CloudUApps22/Forms/List/197
Issue: Cannot delete coop. There is no user assigned to Coop P001 & P002. Please remove coop P001 & P002,
![image](https://github.com/Bizsmartech/DMS2023/assets/111037848/c9709f07-b79d-47f5-86cc-f8feeca01bfc)

**Comment by Atsilah** [comment]
![Link   email User](https://github.com/Bizsmartech/DMS2023/assets/111037848/346be2ff-305b-4bd1-81fd-8fcaa048e77e)

**Comment by induwara99** [comment]
> Induwara said this is the reason why cooperative cannot delete
> 
> Update: Please delete Test User 1 [TBL_User] and Coop ID P002 [Department]
> 
> ![Link email User](https://user-images.githubusercontent.com/111037848/263899622-346be2ff-305b-4bd1-81fd-8fcaa048e77e.jpeg)

Sure!
