### ISSUE TITLE
Deduction Changes: DMID

### ISSUE THREAD

**Issue by Atsilah** [Bizsmartech/DMS2023#2]
Path: http://103.75.190.118/CloudUApps22/Deduction/AddDeduction
![image](https://github.com/Bizsmartech/DMS2023/assets/111037848/a1c56afc-88f7-4118-bb0b-99e0f18fd2b7)

Please set the dropdown to five months forward. 

SP: GET_DMID_LIST

**Comment by induwara99** [comment]
Its Done!
