### ISSUE TITLE
Deduction Report: Add export file 

### ISSUE THREAD

**Issue by Atsilah** [Bizsmartech/DMS2023#3]
Path:  http://103.75.190.118/CloudUApps22/DeductionReport/List
Export file: Excel format
![image](https://github.com/Bizsmartech/DMS2023/assets/111037848/a70c437e-74ae-4029-87c7-fed063dfd8f2)

Follow this file format:
[Deduction Report.xlsx](https://github.com/Bizsmartech/DMS2023/files/12248703/Deduction.Report.xlsx)

**Comment by induwara99** [comment]
DONE! [Deduction-Report.xlsx](https://github.com/Bizsmartech/DMS2023/files/12300987/Deduction-Report.xlsx)
