### ISSUE TITLE
Deduction List : Edit Page (Deduction start) 

### ISSUE THREAD

**Issue by Atsilah** [Bizsmartech/DMS2023#5]
![image](https://github.com/Bizsmartech/DMS2023/assets/111037848/fb051eb2-0097-4b35-bfd3-8a597f383c97)

https://github.com/Bizsmartech/DMS2023/assets/111037848/f5b84683-5e7d-43e8-bc95-7f34d48bb5d1

Right now for edit page , user can change deduction start by select DMID.  (please disable DMID)

Please change to:
1. User are allow to change Deduction Start if date changes is not less than 1 month from the current month. 
For example, user insert Add Deduction start on 202309:

a) When user want to Edit, the system need to set not allowed because right now is 202308 due to 1 month left. Please make it disable.

b) Unless, if user want to edit and change to 202311 is allowed, because the date is more than 1 month ahead. 

The validation for Deduction Start & Deduction End same as task #1

**Comment by induwara99** [comment]
Done!
https://github.com/Bizsmartech/DMS2023/assets/62685893/916ee61d-d546-4803-b104-f8f39a353c7f

**Comment by Atsilah** [comment]
1. Date 202314 doesn't exist, please state as date error.

![image](https://github.com/Bizsmartech/DMS2023/assets/111037848/cf271b50-4557-402d-a2e9-0efc6575b591)

**Comment by induwara99** [comment]
![image](https://github.com/Bizsmartech/DMS2023/assets/62685893/462be3c2-24c3-4750-867e-824acbf81c86)
