### ISSUE TITLE
Add Deduction

### ISSUE THREAD

**Issue by Atsilah** [Bizsmartech/DMS2023#7]
Path: http://103.75.190.118/CloudUApps22/Deduction/AddDeduction

Sometimes when insert New IC, the details of member didnt show up.

https://github.com/Bizsmartech/DMS2023/assets/111037848/c824741d-a99d-4809-873a-1d09ff7e3ad9

**Comment by induwara99** [comment]
All Done!
https://github.com/Bizsmartech/DMS2023/assets/62685893/7d63cc99-25a2-4e33-b4c9-56b45e286b43
