### ISSUE TITLE
Add Deduction : Computerize Default 

### ISSUE THREAD

**Issue by Atsilah** [Bizsmartech/DMS2023#9]
Please make Computerize as default option.
![image](https://github.com/Bizsmartech/DMS2023/assets/111037848/cd84b83e-0d8e-41d0-babf-21e6cccd0468)

**Comment by induwara99** [comment]
DONE!
https://github.com/Bizsmartech/DMS2023/assets/62685893/eb9a69fc-71a6-4ad3-98c7-7f253e7e377c
